### PR TITLE
Support multi-insert

### PR DESCRIPTION
**Pull request by Upliner**

### CODE REVIEW

**Comment by Upliner** [comment]
This patch adds support for statements like INSERT INTO table(a,b,c) VALUES (?,?,?), (?,?,?)

**Comment by kshvakov** [comment]
That is unnecessary

**Comment by kshvakov** [comment]
@jakesyl Hi, see an example https://github.com/ClickHouse/clickhouse-go/blob/master/examples/simple.go#L38

**Comment by jakesyl** [comment]
@kshvakov Appreciate the help. Is this faster than columnar?

**Comment by kshvakov** [comment]
No, but it’s more convenient

**Comment by kshvakov** [comment]
I created [this benchmark]( https://github.com/kshvakov/go-and-clickhouse/tree/master/benchmark) for [Altinity](https://www.altinity.com/)

**Pull request closed without merging**
