### PR TITLE
add test for nil pointers, not just nil literal

### PR DESCRIPTION
**Pull request by derekperkins**
This should work as a basic test case for #124. If you like this direction, I can flesh it out more.

### CODE REVIEW

**Comment by derekperkins** [comment]
I used reflection to check for nil, but I'm not sure how much overhead that adds. Cargo culting from this article, we could replace that code with `unsafe` for performance reasons.
https://dev.to/pauljlucas/go-tcha-when-nil--nil-hic

```
func isNilValue(i interface{}) bool {
    return (*[2]uintptr)(unsafe.Pointer(&i))[1] == 0
}
```

**Comment by derekperkins** [comment]
@kshvakov Does this feel like it is heading it a good direction? It's not working for me locally, but I also don't want to spend a ton more time on it if you don't think it's going to get anywhere.

**Comment by derekperkins** [comment]
I've tested this out in my setup and for some reason it seems to just lock up, but doesn't emit any error messages. I'd really appreciate any guidance you have on the best way to move forward.

**Comment by kshvakov** [comment]
Hi, it's looking good. Thank you!

**Pull request merged**
