### PR TITLE
Fix Readme example registering driver

### PR DESCRIPTION
**Pull request by bithavoc**
Just a simple change to clarify driver registration in the Readme example.

Thanks for such great project BTW 🎉

### CODE REVIEW

**Comment by kshvakov** [comment]
`clickhouse` package is used in type cast (see clickhouse.Exception)

**Comment by bithavoc** [comment]
Why close this? The Readme is still outdated, there are two examples: sqlx works, the first one doesn't. 

This was a fix to that typo.

I don't understand what you're saying about clickhouse.Exception

**Comment by kshvakov** [comment]
If you export package like `_ "github.com/kshvakov/clickhouse"` you''ll receive an error about this 

```go 
if exception, ok := err.(*clickhouse.Exception); ok { // <- undefined: clickhouse
```

**Comment by bithavoc** [comment]
ok ok I see :v:

**Pull request closed without merging**
